// Planet IDE — Browser IDE kernel: file tree, tab lifecycle, command palette, terminal buffer with ANSI parsing.
// Generated by the Counted Repo Factory (seeds/seeds.yaml). Deterministic by construction.
// Layout: docs/REPO_STANDARD.md — core logic in src/lib/, public API in src/index.ts.

import { seededRandom } from "./lib/rng";
import { FileTree, TabManager, CommandPalette, AnsiTerminal } from "./lib/modules";

export const SPEC = "Browser IDE kernel: file tree, tab lifecycle, command palette, terminal buffer with ANSI parsing.";
export const MODULES = [{ id: "FileTree", name: "Planet IDE :: FileTree" }, { id: "TabManager", name: "Planet IDE :: TabManager" }, { id: "CommandPalette", name: "Planet IDE :: CommandPalette" }, { id: "AnsiTerminal", name: "Planet IDE :: AnsiTerminal" }];
export { seededRandom };
export class Registry {
  private items = new Map<string, string>();
  constructor(seed = 42) {
    const rng = seededRandom(seed);
    for (const mod of MODULES) {
      const n = 1 + Math.floor(rng() * 4);
      for (let i = 0; i < n; i++) {
        this.items.set(mod.id + "-" + i, mod.name);
      }
    }
  }
  count(): number { return this.items.size; }
  get(id: string): string | undefined { return this.items.get(id); }
  ids(): string[] { return [...this.items.keys()]; }
  lookup(name: string): string[] {
    return this.ids().filter((id) => this.items.get(id) === name);
  }
}
